services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb_vscode
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=otus_webtours
    volumes:
      - influxdb_vscode_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_vscode
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_vscode_data:/var/lib/grafana
      # Автоматическое подключение Data Source (InfluxDB)
      - ./grafana/provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      # Автоматическая конфигурация путей для дашбордов
      - ./grafana/provisioning/dashboards/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      # Файл самого дашборда
      - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json:ro
    depends_on:
      - influxdb

volumes:
  influxdb_vscode_data:
  grafana_vscode_data:
