apiVersion: 1

datasources:
  - name: webtours
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: otus_webtours
    jsonData:
      httpMode: GET
    isDefault: true
    editable: true
